[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#d51d2a"
backgroundColor = "#f4f5f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#15181d"
font = "sans serif"
